### ISSUE TITLE
Dependency management needed for testing when Golang Modules not used

### ISSUE THREAD

**Issue by bufdev** [jhump/goprotoc#19]
Right now, when Golang Modules are not used in testing, the latest version of each dependency is pulled, not a specific version. This is going to cause breakages with tests at some point, and also makes it difficult for users who do not use Golang Modules to know what versions of dependencies to use.

This probably just means setting up https://github.com/golang/dep so this repository has a `Gopkg.toml` and `Gopkg.lock`.

**Comment by jhump** [comment]
> makes it difficult for users who do not use Golang Modules to know what versions of dependencies to use

Why can those users not just look at `go.mod` to get an idea of what versions to use?

> This is going to cause breakages with tests at some point

That is, to some degree, the point. (Also, of course, making sure it works with other versions/configurations.) I like to know if a dependency adds changes that break my projects. That way I can try to add work-arounds to my project so that it will (hopefully... if possible) work with all versions of the dependency, as far as back as whatever is in `go.mod`. In other repos (like protoreflect and grpcurl), the breakages are rare. In fact, the biggest nuisance I've had is from improvements and new checks being added to `staticcheck` which start finding things in the code that the earlier version of the tool did not find :)

**Comment by bufdev** [comment]
How do users of who do not know what versions to use automatically install their deps? I wouldn't know what to do given the `go.mod` file.

This isn't a matter of all versions, many users specify their default branch as unstable until there's a release. For example, this is how all Uber OSS code is - the `dev` branch is unstable and can change pre-release, but this is the branch you will download automatically if you have no pinning.

That the breakages are rare doesn't make this correct - in the Golang Modules tests, you're pinning versions, but in the non-Golang Modules tests, you're using the latest. That doesn't seem right. Specifically re: #18 I expect the API to change a lot, so we couldn't merge that without locking.

If you want to know if a dependency adds changes that cause breakages, you should update your `Gopkg.toml` file. What you're doing by not having locking is making testing non-deterministic and not reproducible.

I don't think there is any downside to having your dependencies locked, it's a best-practice, and it only adds issues and a lack of reproducibility.

> That way I can try to add work-arounds to my project so that it will (hopefully... if possible) work with all versions of the dependency.

This isn't what is happening though - you're only making sure it works with the latest (as of the time a Travis run happens) version. You're actually specifically not testing that your code works against previous versions. People introduce breaking changes on their default branch all the time, not everyone conforms to SemVer unfortunately. I wish it weren't so :-)

**Comment by bufdev** [comment]
Talked offline, closing this, not worth it for now
