### ISSUE TITLE
How to get extend options of a message?

### ISSUE THREAD

**Issue by ZhiruiLi** [jhump/goprotoc#29]
Hi, sometimes we need to defined some extend options, but it seems that goprotoc does not expose any interface for us to get our options. For example, here is my .proto file:

```protobuf
syntax = "proto3";

import "google/protobuf/descriptor.proto";

extend google.protobuf.MessageOptions {
    string my_option = 51234;
}

message A {
    option (my_option) = "Hello world!";
}
```

If I print out the message options in the example callback, like this:

```go
func doCodeGen(req *plugins.CodeGenRequest, rsp *plugins.CodeGenResponse) error {
    fmt.Println(req.Files[0].GetMessageTypes()[0].GetMessageOptions())
}
```

I will get these output in console:

```
51234:"Hello world!" 
```

It seems that user defined options is recorded in some map, but there is no way for me to get the option `my_option` by myself. By the way, I tried to find the option by `GetUninterpretedOption` method, but the following code returns `0`.

```go
len(req.Files[0].GetMessageTypes()[0].GetMessageOptions().GetUninterpretedOption())
```

**Comment by ZhiruiLi** [comment]
should use `proto.GetExtension(msg.GetOptions(), ...)`

**Comment by jhump** [comment]
@ZhiruiLi, note that `proto.GetExtension` only works if your plugin has that custom option compiled and linked into it. In other words, you have to compile the `.proto` file that defines the custom option and link the generated code into your plugin.

If you want to be able to examine other options, including those that your plugin was not compiled to know about, you can convert the options to a `*dynamic.Message`. This requires a few steps to work correctly:

1. Create a `*dynamic.ExtensionRegistry`.
2. [Add all](https://godoc.org/github.com/jhump/protoreflect/dynamic#ExtensionRegistry.AddExtensionsFromFile) files the plugin receives to the registry.
3. Use that registry to [convert the options message](https://godoc.org/github.com/jhump/protoreflect/dynamic#AsDynamicMessageWithExtensionRegistry) to a dynamic one.

The dynamic message has fields for enumerating the message's fields. You'll see `desc.FileDescriptor`s for each field and also see an `interface{}` value. The types of those values are the Go types that correspond to the proto field type, just `protoc-gen-go` uses for generating fields. More info [here](https://godoc.org/github.com/jhump/protoreflect/dynamic#Message.TryGetField).

You need the extension registry so that the dynamic message can correctly interpret the custom option. Otherwise, it is considered an unrecognized field. Adding all of the files that the plugin receives creates a sufficient registry because the file that uses an option _must_ import it, so the imported file (the one that defines the option) will be present in the set of files that protoc sends to the plugin.
