### ISSUE TITLE
goprotoc does not correctly generate a ZIP or JAR file when that is given as output location

### ISSUE THREAD

**Issue by jhump** [jhump/goprotoc#9]
If I give an output location that is a ZIP or JAR file, goprotoc instead just creates files in the parent directory of the expected location.

**Comment by bufdev** [comment]
This should be as expected. If given a jar or zip file output, it should create a jar or zip in the parent directory, this is right. I’ll test vs. protoc but I think this is as intended unless I’m missing something.

**Comment by jhump** [comment]
It turns out that the behavior is only wrong when goprotoc runs plugins. When it runs protoc (to generate a language that protoc handles, like java), it works fine (because it's protoc that is putting everything into a ZIP/JAR).

**Comment by bufdev** [comment]
From my testing, it actually doesn’t work fine with builtins - I tested with java, outputting to java.jar as an example, and it made a directory named java.jar, not a jar file named java.jar. This is because when goprotoc proxies to protoc, it gives the out as a directory, not as a file with a jar or zip suffix. This part is an easy fix though

**Comment by jhump** [comment]
Okay. So broken in both paths, but the paths require two different fixes. Thanks for testing it!
